name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        default: "v0.0.0"
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Compilers
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    - name: Setup Dependencies
      run: ./setup.sh windows
    - name: make Windows
      run: make PLATFORM=windows
    - name: Package Windows
      run: zip fantasia-windows_x86_64.zip ./bin
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          fantasia-windows_x86_64.zip
