name: Build and Release

on:
  workflow_dispatch:
    inputs:
      major:
        description: "Major version"
        required: true
        default: "0"
      minor:
        description: "Minor version"
        required: true
        default: "0"
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Computer version
      id: version
      run: |
        VERSION=v${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.run_number }}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Install Compilers
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential mingw-w64
    - name: Setup Dependencies
      run: ./setup.sh windows
    - name: make Windows
      run: make PLATFORM=windows
    - name: Package Windows
      run: zip fantasia-windows_x86_64.zip ./bin
    - name: Create tag
      run: |
        git tag $VERSION
        git push origin $VERSION
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        files: |
          fantasia-windows_x86_64.zip
